name: VS Code Extension CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 新增：支持手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [">16.x"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache VS Code download
        id: cache-vscode
        uses: actions/cache@v3
        with:
          path: .vscode-test
          key: ${{ runner.os }}-vscode-${{ hashFiles('package.json') }}-${{ '1.94.2' }}

      - name: Check cache status
        run: |
          if [ "${{ steps.cache-vscode.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit, skipping download."
          else
            echo "Cache miss, downloading VS Code."
          fi

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Compile code
        run: npm run compile

      - name: Compile tests
        run: npm run compile-tests

      - name: Set VS Code version environment variable
        run: echo "VSCODE_VERSION=1.94.2" >> $GITHUB_ENV

      - name: Run tests
        env:
          VSCODE_CACHE_PATH: .vscode-test
          USE_VSCODE_VERSION_FROM_ENV: true  # 假设测试脚本支持通过环境变量指定版本
        run: npm test

      - name: Package extension
        if: github.ref == 'refs/heads/main'
        run: npm run package

      - name: Publish extension (if tagged release)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --pat $VSCE_PAT
    